#!/usr/bin/env bash
# Kamadhenu
# an udderly abmurd moothmayer in your mhell

#!/usr/bin/env bash
# vim: noai:ts=4:sw=4:expandtab
# shellcheck source=/dev/null
# shellcheck disable=2009
#
# Neofetch: A command-line system information tool written in bash 3.2+.
# https://github.com/dylanaraps/neofetch
#
# The MIT License (MIT)
#
# Copyright (c) 2015-2020 Dylan Araps
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version=7.1.0

# Fallback to a value of '5' for shells which support bash
# but do not set the 'BASH_' shell variables (osh).
bash_version=${BASH_VERSINFO[0]:-5}
shopt -s eval_unsafe_arith &>/dev/null

sys_locale=${LANG:-C}
XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-${HOME}/.config}
PATH=$PATH:/usr/xpg4/bin:/usr/sbin:/sbin:/usr/etc:/usr/libexec
reset='\e[0m'
shopt -s nocasematch

# Speed up script by not using unicode.
LC_ALL=C
LANG=C

# Neofetch default config.
# read -rd '' config <<'EOF'


KM_DIR="$(brew --prefix)"
# KM_DIR="$(dirname "$(readlink "$0")")"
KMD_COLS=$(($(tput cols)-3))
MAX_COLS=128
COW_OPTS=''
LOL_OPTS='-ats 40 -d 4 -p 3 -F .125'
CUTOFF=1024

[[ $KMD_COLS -lt $MAX_COLS ]] || KMD_COLS=$MAX_COLS

randomize() {
    unset COW
    COW=$(basename "$(find "$KM_DIR/share/cowsay/cows/"*.cow | shuf -n 1)")
    unset FONT
    FONT=$(basename "$(find "$KM_DIR/share/figlet/fonts/"*.flf | shuf -n 1)")
}

printFortune() {
    randomize
    unset COW_OPTS && COW_OPTS="-W ${KMD_COLS} -f ${COW}"
    if [ "$1" == "0" ]; then
        exit 0
    elif [ -z "$1" ] || [ "$1" == "1" ]; then
        LOL_OPTS=''
        fortune -sn 320 | cowsay $COW_OPTS | lolcat $LOL_OPTS
        exit 0
    elif [ "$1" == "help" ] || [ "$1" == '-h' ] ; then
        introMsg | lolcat ${LOL_OPTS}
        figlet -w 48 -cf cybermedium 'Kamadhenu' | lolcat $LOL_OPTS
        sleep 1
        errorMsg | lolcat $LOL_OPTS
        sleep 2
        beginMsg | lolcat $LOL_OPTS
        sleep 1
        prompt
    elif [[ $1 =~ ^-?[1-9]+$ ]]; then
        fortune -sn 320 | cowsay $COW_OPTS | lolcat $LOL_OPTS
        echo "$(($1 - 1)) remaining" && read -rsp $'Press any key to continue…
        or Ctrl-C yourself out\n' -n 1 key
        printFortune $(($1 - 1))
    else
        if [ ${#1} -le 14 ]; then
            figlet -w $KMD_COLS -f "$FONT" "$1" | cowsay -n $COW_OPTS | lolcat $LOL_OPTS
        elif [ ${#1} -le "$CUTOFF" ]; then
            echo "$1" | cut -c -$CUTOFF | cowsay $COW_OPTS | lolcat $LOL_OPTS
        fi
        printf '%*s' "$(tput cols)"  Kamadhenu
    fi
    prompt
}

# I am the gatekeeper. Are you the keymaster?

prompt() {
    unset INPUT
    promptMsg | lolcat $LOL_OPTS
    read -rep "$PROMPT" INPUT
    printFortune "$INPUT"
}

introMsg() {
    cat << EOF
                    {}}
                   {{}{}
                  {{}}{}}
                 &>&&&&?&@
               &&@&&&@*&@#&#@
            &&&&#&*&&&&@&&&#&&&@
         &#&&@&&$&&&&&&&&&&&@&#&*&@
      &&*$&&$&7&&&$&>&&&&?&&&<&#&$&&#@
   &&&&&&$&&&&@&!&&&&&&&&&&&&#&*&#&&@>*&&
 &&!*&#+&&&&&!&<@&?&&&&?&&@&&/&#@&&&#&<&@&&&
&*  Prostrate yourself before the Almighty  &@
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOF
}

beginMsg() {
    cat << EOF

          Now, let's cast your lots.
_.--._._._.--._..-.-.___.--._.__..__._._._.-..
^^+~*^^**^*~*^*^*~^*^*^*^*~^*~*^+^+^^^+^^+^^+^
EOF
}

errorMsg() {
    cat << EOF
_.-^-.__._.-..-.__.__._.-^-.__.-.._..-..__.-._
^^+~*^^**^*~*^*^*~^*^*^*^*~^*~*^+^+^^^+^^+^^+^
   You may Ctrl-c yourself out at any time.
_.--._._._.--._..-.-.___.--._.__..__._._._.-..
EOF
}

promptMsg() {
    cat << EOF


_.-^-.__._.-..-.__.__._.-^-.__.-.._..-..__.-._
+^+=^=+^+=+^+^+^==^+^+^+=+^+=^+^+=^=+^+=+^+^+^
       You may put words in my mouth,
         or <ENTER> if you dare.
;,:.,:;,.,.:;.,.;:..,;.,:.;..;.,.;:..,;.,:.;..
EOF
}

PROMPT="\$ "

# Call upon Kamadhenu!
printFortune "$1"
